variables = {}

variables["ge4j_ge4t"] = [
    "Evt_CSV_avg_tagged",
    "Evt_CSV_avg",
    "Evt_M_minDrLepTag",
    "Evt_Pt_JetsAverage",
    "Evt_Pt_minDrTaggedJets",
    "Evt_Deta_TaggedJetsAverage",
    "Evt_Deta_JetsAverage",
    "N_Jets",
    "Reco_JABDT_ttbar_Jet_CSV_whaddau2",
    "Reco_ttbar_toplep_m",
    "Reco_tHq_bestJABDToutput",
    "Reco_JABDT_tHq_abs_ljet_eta",
    "Reco_JABDT_tHq_Jet_CSV_hdau1",
    "Reco_JABDT_tHW_Jet_CSV_btop",
    "memDBp",

    # failed 2D validation
    # "Evt_M_JetsAverage",
    # "Reco_ttbar_bestJABDToutput",
    # "Reco_ttH_toplep_m",
    # "Reco_ttH_bestJABDToutput",
    # "Evt_blr_transformed",
    # "Reco_JABDT_ttH_Jet_CSV_hdau2",
    # "Reco_JABDT_ttbar_Jet_CSV_whaddau1",

    # failed 2D validation with lnN
    # "Reco_tHW_bestJABDToutput",
    # "Reco_JABDT_tHW_top_pt__P__h_pt__P__wb_pt__DIV__Evt_HT__P__Evt_Pt_MET__P__Lep_Pt",
    # "Reco_JABDT_tHW_Jet_CSV_whaddau1",
    # "CSV[2]",
    # "Evt_M_TaggedJetsAverage",

#    'Jet_btagValue[0]',
#    'Jet_btagValue[1]',
#    'Jet_btagValue[2]',
#    'Jet_btagValue[3]',
#    'Jet_btagValue[4]',
#    'Jet_btagValue[5]',

    'Jet_CSV[0]',
    'Jet_CSV[1]',
    'Jet_CSV[2]',
    'Jet_CSV[3]',
    'Jet_CSV[4]',
    'Jet_CSV[5]',

    'Jet_E[0]',
    'Jet_E[1]',
    'Jet_E[2]',
    'Jet_E[3]',
    'Jet_E[4]',
    'Jet_E[5]',
    'Jet_Eta[0]',
    'Jet_Eta[1]',
    'Jet_Eta[2]',
    'Jet_Eta[3]',
    'Jet_Eta[4]',
    'Jet_Eta[5]',
    'Jet_M[0]',
    'Jet_M[1]',
    'Jet_M[2]',
    'Jet_M[3]',
    'Jet_M[4]',
    'Jet_M[5]',
    'Jet_Phi[0]',
    'Jet_Phi[1]',
    'Jet_Phi[2]',
    'Jet_Phi[3]',
    'Jet_Phi[4]',
    'Jet_Phi[5]',
    'Jet_Pt[0]',
    'Jet_Pt[1]',
    'Jet_Pt[2]',
    'Jet_Pt[3]',
    'Jet_Pt[4]',
    'Jet_Pt[5]',
    'TightLepton_E[0]',
    'TightLepton_Eta[0]',
    'TightLepton_M[0]',
    'TightLepton_Phi[0]',
    'TightLepton_Pt[0]',

    ]

variables["ge4j_3t"] = [
    "memDBp",
    "Evt_Deta_JetsAverage",
    "Evt_M_TaggedJetsAverage", 
    "Evt_CSV_avg", 
    "Evt_blr_transformed",
    "N_Jets",
    "Reco_ttbar_toplep_m",
    "Reco_ttbar_whad_m",
    "Reco_JABDT_ttH_Jet_CSV_btoplep",
    "Reco_JABDT_tHW_log_wb_m",

    # failed 2D validation
    # "Evt_CSV_dev",
    # "Evt_M_Total",
    # "Evt_CSV_avg_tagged",
    # "Reco_ttH_bestJABDToutput",
    # "Reco_tHq_bestJABDToutput",
    # "Reco_tHW_whad_dr",
    # "Reco_tHW_bestJABDToutput",
    # "Reco_JABDT_tHW_Jet_CSV_btop",
    # "Reco_JABDT_tHW_Jet_CSV_whaddau1",
    # "Reco_ttbar_bestJABDToutput",  
    # "Reco_JABDT_ttbar_Jet_CSV_btophad",
    # "Reco_JABDT_ttbar_Jet_CSV_btoplep",
   
    # failed 2D validation with lnN
    # "Reco_JABDT_ttbar_Jet_CSV_whaddau1",
    # "Evt_JetPt_over_JetE",
    # "Evt_h1",
    # "Evt_Pt_minDrTaggedJets",
    # "Evt_HT_tags",
    # "Evt_Deta_TaggedJetsAverage",
    # "Evt_M_JetsAverage"


    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
